FROM node:12.14.0

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

WORKDIR /app
COPY ./package*.json ./
# Install dev dependencies to allow building with webpack
RUN npm ci --no-optional
RUN npm list webpack
COPY . .
RUN npm run generate:docs k8s && \
  npm run build
CMD ["npm", "run", "start"]